# test config mushra page, 2 trials: 1) not randomized, condition names shown 2) 

testname: MUSHRA Masterarbeit Otto Fritzsch
testId: mushra_norandom
bufferSize: 2048
stopOnErrors: false
showButtonPreviousPage: true
remoteService: service/write.php


pages:

    - type: mushra
      id: trial1
      name: Akkordwechsel
      content: Bitte hören Sie sich alle Versionen sorgfältig an und bewerten Sie jede auf einer Skala von 0 (sehr unterschiedlich) bis 100 (identisch).
      showWaveform: true
      enableLooping: true
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: true
      createAnchor70: false
      randomize: true
      showConditionNames: false
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          

    - type: finish
      name: Thank you
      content: Thank you for attending
      popupContent: Your results were sent. Goodbye and have a nice day      
      showResults: true
      writeResults: true
